# Generated by Django 6.0.4 on 2026-04-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='材料类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='材料类型名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('allowed_extensions', models.CharField(blank=True, help_text='多个后缀使用英文逗号分隔，例如 pdf,doc,docx', max_length=200, verbose_name='允许后缀')),
                ('max_size_mb', models.PositiveIntegerField(default=30, verbose_name='大小上限(MB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '材料类型',
                'verbose_name_plural': '材料类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_role', models.IntegerField(choices=[(1, '学院领导'), (2, '管理老师'), (3, '班团骨干')], default=2, verbose_name='审批角色')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='任务状态')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('can_withdraw_until', models.DateTimeField(blank=True, null=True, verbose_name='可撤回截止时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批任务',
                'verbose_name_plural': '审批任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交审批'), ('approve', '通过'), ('reject', '驳回'), ('withdraw', '撤回'), ('reopen', '重开')], max_length=20, verbose_name='动作')),
                ('comment', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='party.partyapprovaltask', verbose_name='审批任务')),
            ],
            options={
                'verbose_name': '审批动作记录',
                'verbose_name_plural': '审批动作记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('party', '入党流程'), ('league', '入团流程')], default='party', max_length=20, verbose_name='流程类型')),
                ('current_stage', models.CharField(choices=[('applicant', '申请人'), ('activist', '积极分子'), ('candidate', '发展对象'), ('probationary', '预备党员'), ('full', '正式党员')], default='applicant', max_length=20, verbose_name='当前阶段')),
                ('status_since', models.DateField(blank=True, null=True, verbose_name='进入当前阶段日期')),
                ('expected_next_date', models.DateField(blank=True, null=True, verbose_name='预计下一节点日期')),
                ('is_locked', models.BooleanField(default=False, verbose_name='流程锁定')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_party_profiles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_profile', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '党团发展档案',
                'verbose_name_plural': '党团发展档案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyStageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='节点编码')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('track_type', models.CharField(choices=[('party', '入党流程'), ('league', '入团流程')], default='party', max_length=20, verbose_name='流程类型')),
                ('stage', models.CharField(choices=[('applicant', '申请人'), ('activist', '积极分子'), ('candidate', '发展对象'), ('probationary', '预备党员'), ('full', '正式党员')], max_length=20, verbose_name='对应阶段')),
                ('order', models.PositiveIntegerField(verbose_name='排序')),
                ('min_duration_days', models.PositiveIntegerField(default=0, verbose_name='最短停留天数')),
                ('requires_training', models.BooleanField(default=False, verbose_name='是否要求培训合格')),
                ('target_role_for_approval', models.IntegerField(choices=[(1, '学院领导'), (2, '管理老师'), (3, '班团骨干')], default=2, verbose_name='审批角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='节点说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流程节点定义',
                'verbose_name_plural': '流程节点定义',
                'ordering': ['track_type', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('track_type', 'code'), name='uniq_party_stage_def_track_code'), models.UniqueConstraint(fields=('track_type', 'order'), name='uniq_party_stage_def_track_order')],
            },
        ),
        migrations.CreateModel(
            name='PartyStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('open', '进行中'), ('submitted', '已提交审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='节点状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='party.partymemberstatus', verbose_name='党团发展档案')),
                ('stage_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='party.partystagedefinition', verbose_name='节点定义')),
            ],
            options={
                'verbose_name': '节点实例',
                'verbose_name_plural': '节点实例',
                'ordering': ['member', 'stage_definition__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('material_due', '材料截止提醒'), ('stage_ready', '节点可推进提醒'), ('approval_pending', '审批待办提醒'), ('overdue', '逾期提醒')], max_length=30, verbose_name='提醒类型')),
                ('channel', models.CharField(choices=[('site', '站内'), ('email', '邮件'), ('wechat', '微信')], default='site', max_length=20, verbose_name='渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='发送状态')),
                ('title', models.CharField(max_length=200, verbose_name='提醒标题')),
                ('content', models.TextField(blank=True, verbose_name='提醒内容')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划发送时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='实际发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='party.partymemberstatus', verbose_name='党团发展档案')),
                ('stage_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='party.partystageinstance', verbose_name='节点实例')),
            ],
            options={
                'verbose_name': '流程提醒',
                'verbose_name_plural': '流程提醒',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMaterialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='party/materials/', verbose_name='材料文件')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_party_materials', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_party_materials', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='party.partymaterialtype', verbose_name='材料类型')),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_submissions', to='party.partystageinstance', verbose_name='节点实例')),
            ],
            options={
                'verbose_name': '材料提交',
                'verbose_name_plural': '材料提交',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='partyapprovaltask',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='party.partystageinstance', verbose_name='节点实例'),
        ),
        migrations.CreateModel(
            name='PartyStageMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='提交说明')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_requirements', to='party.partymaterialtype', verbose_name='材料类型')),
                ('stage_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='party.partystagedefinition', verbose_name='流程节点')),
            ],
            options={
                'verbose_name': '节点材料要求',
                'verbose_name_plural': '节点材料要求',
                'ordering': ['stage_definition', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='partystageinstance',
            constraint=models.UniqueConstraint(fields=('member', 'stage_definition'), name='uniq_party_stage_instance'),
        ),
        migrations.AddConstraint(
            model_name='partystagematerialrequirement',
            constraint=models.UniqueConstraint(fields=('stage_definition', 'material_type'), name='uniq_party_stage_material_requirement'),
        ),
    ]
