# Generated by Django 6.0.5 on 2026-05-11 07:09
#
# Kept as a no-op compatibility migration.
# The current 0001_initial migration already creates the PartyMemberStatus.user
# relation and the old PartyProgressRecord model no longer exists.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0001_initial"),
    ]

    operations = []
