# Generated by Django 4.2.30 on 2026-05-23 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='工作描述')),
                ('work_date', models.DateField(verbose_name='工作日期')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='工时')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_works', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作量记录',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='荣誉名称')),
                ('category', models.CharField(choices=[('academic', '学术竞赛'), ('sports', '文体活动'), ('social', '社会实践'), ('volunteer', '志愿服务'), ('party', '党团活动'), ('other', '其他')], default='other', max_length=50, verbose_name='奖项类别')),
                ('level', models.CharField(max_length=50, verbose_name='级别')),
                ('description', models.TextField(blank=True, default='', verbose_name='奖项描述')),
                ('awarded_at', models.DateField(verbose_name='获奖日期')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='profile/honors/', verbose_name='证明材料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '荣誉记录',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
