# Generated by Django 4.2.30 on 2026-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                    ("expired", "已过期"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
